[profile.default]
src = "src"
out = "artifacts"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
TestChainA = "http://18.196.63.236:8545"
TestChainB = "http://3.79.184.123:8545"

# forge script script/DeployHook.s.sol:DeployTestChainA --rpc-url TestChainA --via-ir --private-key ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --code-size-limit 30000 --broadcast 

# forge script script/DeployHook.s.sol:DeployTestChainB --rpc-url TestChainB --via-ir --private-key ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --code-size-limit 30000 --broadcast 